#!/usr/bin/env python3
"""Generate snat-config.nix from general_config.toml."""

from __future__ import annotations

import argparse
import ipaddress
import json
import re
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent


def port_number(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value <= 65535:
        raise ValueError(f"{field} must be an integer between 1 and 65535")
    return value


def load_config(path: Path) -> tuple[str, bool, list[dict[str, Any]]]:
    with path.open("rb") as file:
        config = tomllib.load(file)

    snat = config.get("snat")
    if not isinstance(snat, dict):
        raise ValueError("missing [snat] table")

    interface = snat.get("external_interface")
    if not isinstance(interface, str) or not re.fullmatch(r"[A-Za-z0-9_.:-]{1,15}", interface):
        raise ValueError("snat.external_interface must be a valid interface name")

    masquerade = snat.get("masquerade", True)
    if not isinstance(masquerade, bool):
        raise ValueError("snat.masquerade must be a boolean")

    ports = snat.get("ports", [])
    if not isinstance(ports, list):
        raise ValueError("snat.ports must be an array of tables")

    normalized = []
    seen = set()
    for index, entry in enumerate(ports, start=1):
        if not isinstance(entry, dict):
            raise ValueError(f"snat.ports entry {index} must be a table")

        protocol = entry.get("protocol", "tcp")
        if protocol not in {"tcp", "udp"}:
            raise ValueError(f"snat.ports entry {index}: protocol must be tcp or udp")

        external_port = port_number(
            entry.get("external_port"), f"snat.ports entry {index}: external_port"
        )
        target_port = port_number(
            entry.get("target_port"), f"snat.ports entry {index}: target_port"
        )
        target_host = entry.get("target_host")
        if not isinstance(target_host, str):
            raise ValueError(
                f"snat.ports entry {index}: target_host must be an IPv4 address"
            )
        try:
            target_host = str(ipaddress.IPv4Address(target_host))
        except ipaddress.AddressValueError as error:
            raise ValueError(
                f"snat.ports entry {index}: target_host must be an IPv4 address"
            ) from error

        key = (protocol, external_port)
        if key in seen:
            raise ValueError(
                f"duplicate external port: {protocol}/{external_port}"
            )
        seen.add(key)
        normalized.append(
            {
                "protocol": protocol,
                "external_port": external_port,
                "target_host": target_host,
                "target_port": target_port,
            }
        )

    return interface, masquerade, normalized


def nix_port_list(name: str, ports: list[int]) -> list[str]:
    lines = [f"  networking.firewall.{name} = ["]
    lines.extend(f"    {port}" for port in ports)
    lines.append("  ];")
    return lines


def render_toml(interface: str, masquerade: bool, ports: list[dict[str, Any]]) -> str:
    lines = [
        "[snat]",
        f"external_interface = {json.dumps(interface)}",
        f"masquerade = {'true' if masquerade else 'false'}",
    ]
    for entry in ports:
        lines.extend(
            [
                "",
                "[[snat.ports]]",
                f"protocol = {json.dumps(entry['protocol'])}",
                f"external_port = {entry['external_port']}",
                f"target_host = {json.dumps(entry['target_host'])}",
                f"target_port = {entry['target_port']}",
            ]
        )
    return "\n".join(lines) + "\n"


def render(interface: str, masquerade: bool, ports: list[dict[str, Any]]) -> str:
    tcp_ports = sorted(
        entry["external_port"] for entry in ports if entry["protocol"] == "tcp"
    )
    udp_ports = sorted(
        entry["external_port"] for entry in ports if entry["protocol"] == "udp"
    )
    quoted_interface = json.dumps(interface)

    lines = [
        "# Generated by generate_snat_config.py from general_config.toml.",
        "# Edit general_config.toml, then run: ./generate_snat_config.py",
        "{ ... }:",
        "",
        "{",
    ]
    if tcp_ports:
        lines.extend(nix_port_list("allowedTCPPorts", tcp_ports))
        lines.append("")
    if udp_ports:
        lines.extend(nix_port_list("allowedUDPPorts", udp_ports))
        lines.append("")

    lines.extend(
        [
            "  networking.nftables.tables.nat = {",
            '    family = "ip";',
            "    content = ''",
            "      chain postrouting {",
            "        type nat hook postrouting priority srcnat;",
        ]
    )
    if masquerade:
        lines.append(f"        oifname {quoted_interface} masquerade")
    lines.extend(
        [
            "      }",
            "",
            "      chain prerouting {",
            "        type nat hook prerouting priority dstnat;",
        ]
    )
    for entry in ports:
        lines.append(
            f"        iifname {quoted_interface} {entry['protocol']} "
            f"dport {entry['external_port']} dnat to "
            f"{entry['target_host']}:{entry['target_port']}"
        )
    lines.extend(["      }", "    '';", "  };", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=ROOT / "general_config.toml",
        help="input TOML file (default: general_config.toml beside this script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "snat-config.nix",
        help="output Nix file (default: snat-config.nix beside this script)",
    )
    args = parser.parse_args()

    try:
        interface, masquerade, ports = load_config(args.config)
        content = render(interface, masquerade, ports)
        args.output.write_text(content, encoding="utf-8")
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        parser.error(str(error))

    print(f"generated {args.output} ({len(ports)} port forwards)")


if __name__ == "__main__":
    main()
